# SPDX-License-Identifier: GPL-2.0
obj-y := base.o property.o
obj-$(CONFIG_OF_FLATTREE) += fdt.o
obj-$(CONFIG_OF_EARLY_FLATTREE) += fdt_address.o
obj-$(CONFIG_OF_RESERVED_MEM) += of_reserved_mem.o
obj-$(CONFIG_OF_NUMA) += of_numa.o
obj-$(CONFIG_OF_IRQ)    += irq.o
