#!/bin/sh

qemu-system-aarch64 -cpu cortex-a57 -machine type=virt,gic-version=3 	\
		-append "rdinit=/linuxrc console=ttyAMA0 earlycon=115200"	\
		-kernel ../../arch/arm64/boot/Image	\
		-device virtio-scsi-device	\
		-smp cores=4,threads=5	\
		-m 2G	\
        -object memory-backend-ram,id=mem0,size=512M \
        -object memory-backend-ram,id=mem1,size=128M \
        -object memory-backend-ram,id=mem2,size=256M \
        -object memory-backend-ram,id=mem3,size=1G \
		-object memory-backend-ram,id=mem4,size=128M \
		-numa node,memdev=mem0,cpus=8-11,nodeid=0 \
        -numa node,memdev=mem1,cpus=4-7,cpus=12,nodeid=1 \
		-numa node,memdev=mem2,cpus=13-15,nodeid=2 \
        -numa node,memdev=mem3,cpus=16-19,nodeid=3 \
		-numa node,memdev=mem4,cpus=0-3,nodeid=4 \
		-numa dist,src=0,dst=0,val=10	\
		-numa dist,src=0,dst=1,val=15	\
		-numa dist,src=0,dst=2,val=20	\
		-numa dist,src=0,dst=3,val=15	\
		-numa dist,src=0,dst=4,val=10	\
		-numa dist,src=1,dst=1,val=10	\
		-numa dist,src=1,dst=2,val=25	\
		-numa dist,src=1,dst=3,val=15	\
		-numa dist,src=1,dst=4,val=10	\
		-numa dist,src=2,dst=2,val=10	\
		-numa dist,src=2,dst=3,val=30	\
		-numa dist,src=2,dst=4,val=10	\
		-numa dist,src=3,dst=3,val=10	\
		-numa dist,src=3,dst=4,val=15	\
		-numa dist,src=4,dst=4,val=10	\
		-serial stdio 	\
		-s -S
