# SPDX-License-Identifier: GPL-2.0
#
# Makefile for some libs needed in the kernel.
#
obj-y += bitmap.o find_bit.o

# TODO
obj-$(CONFIG_GENERIC_ATOMIC64) += atomic64.o
obj-$(CONFIG_GENERIC_HWEIGHT) += hweight.o

lib-y := ctype.o string.o
