# SPDX-License-Identifier: GPL-2.0
obj-y := time.o timer.o
obj-y += clocksource.o jiffies.o tick-sched.o
obj-y += clockevents.o tick-common.o hrtimer.o tick-oneshot.o
obj-y += timecounter.o timekeeping.o ntp.o timeconv.o
