# SPDX-License-Identifier: GPL-2.0
lib-y := strcmp.o strncmp.o strchr.o strrchr.o	\
	strlen.o strnlen.o memcmp.o memchr.o memcpy.o	\
	memmove.o memset.o bitops.o clear_page.o clear_user.o	\
	copy_from_user.o copy_in_user.o copy_page.o copy_to_user.o

obj-$(CONFIG_CRC32) += crc32.o
